#!C:\Users\NIKHIL\AppData\Local\Programs\Python\Python38-32\python.exe
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>LOGIN PAGE</title>")
print("</head>")
print("<body>")
print("<h3>Hello USER!</h3>")
print("<form action='q16_check.py' method='post'>")
print("<label>Username</label>")
print("<input type='text' id='uname' name='uname' placeholder='USERNAME' required>")
print("<label>Password</label>")
print("<input type='password' id='pswd' name='pswd' placeholder='********' required >")
print("<button type='submit' value='submit' > SUBMIT</button>")
print("</form>")
print("</body>")
print("</html>")