#!C:\Users\NIKHIL\AppData\Local\Programs\Python\Python38-32\python.exe
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>Python Assignment</title>")
print("</head>")
print("<body>")
print("<h3>  Text field Details to be reversed </h3>")
print("<form action='/submit.py' method='get'>")
print("<label for='first'> enter the details here</label>")
print("<textarea name='text_feild' id='text_feild' rows='6' cols='50'>")
print("</textarea> ")
print("<button type='submit' value='submit' > SUBMIT</button>")
print("<button type='reset'>Reset</button")
print("</form>")

print("</body>")
print("</html>")